---
- name: Check if firewalld package is installed
  command: yum list installed firewalld
- name: Disable the firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: false
  
