---

- name: Download JBoss from jboss.org
  get_url: 
   url: https://github.com/wildfly/wildfly/releases/download/25.0.0.Final/wildfly-preview-25.0.0.Final.zip
   dest: /opt/wildfly-preview-25.0.0.Final.zip

- name: Extract archive
  command: chdir=/usr/share /usr/bin/zip -q /opt/wildfly-preview-25.0.0.Final.zip creates=/usr/share/jboss-as

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv wildfly-preview-25.0.0.Final jboss-as creates=/usr/share/jboss-as

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group: name=jboss

- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as

- name: Change ownership of JBoss installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes

- name: Copy the init script
  copy: src=wildfly-init-redhat.sh dest=/etc/init.d/jboss mode=0755

- name: Enable JBoss to be started at boot
  service: name=jboss enabled=yes state=started 
