---
jcliff_package_name: jcliff
jcliff_program_name: jcliff
jcliff_homebrew_tap: redhat-cop/redhat-cop
jcliff_install_matrix:
  rpm:
    - Fedora
    - CentOS
    - RedHat
  homebrew:
    - MacOSX
jcliff_yumrepository:
  skip: "{{ override_jcliff_yumrepository_skip | default('False') }}"
  enabled: "{{ override_jcliff_yumrepository_enabled | default('true') }}"
  gpgcheck: "{{ override_jcliff_yumrepository_gpgcheck | default('1') }}"
  gpgkey: "{{ override_jcliff_yumrepository_gpgkey | default('https://download.copr.fedorainfracloud.org/results/ansiblemiddleware/jcliff/pubkey.gpg') }}"
  baseurl: "{{ override_jcliff_yum_baseurl | default('https://download.copr.fedorainfracloud.org/results/ansiblemiddleware/jcliff/epel-8-$basearch/') }}"

jcliff_standalone: false
jcliff_standalone_version_latest: true
jcliff_standalone_version: 2.12.8
jcliff_standalone_archive: "https://github.com/bserdar/jcliff/releases/download/v{{ jcliff_standalone_version }}/jcliff-{{ jcliff_standalone_version }}-dist.tar.gz"
jcliff_standalone_root: "/usr/share"
jcliff_standalone_home_dir: "{{ jcliff_standalone_root }}/{{ jcliff_program_name }}-{{ jcliff_standalone_version }}"
jcliff_standalone_commmon_link: "{{ jcliff_standalone_root }}/{{ jcliff_program_name }}"
jcliff_standalone_binary_dir: "/usr/bin"
